// AUTO-GENERATED from src/index.js by scripts/build-standalone.js
// DO NOT EDIT THIS FILE DIRECTLY. Edit src/index.js and run:
//   npm run build:standalone
//
// Standalone IIFE — what gets served at https://ownify.ai/chat-widget.js
// for zero-config <script> tag use. Auto-bootstraps on DOMContentLoaded.
//
// For npm/build-system use, import { mountOwnifyChat } from
// 'ownify-chat-widget' (ESM, src/index.js).

(function () {
  'use strict';

  // Capture the script tag's CSP nonce at IIFE entry — by the time
  // DOMContentLoaded fires, document.currentScript is null. If the
  // embedding page loaded the script with a nonce (e.g. <script
  // src=".../chat-widget.js" nonce="abc123">), that nonce gets
  // propagated to every widget mount's injected <style> tag without
  // the embedder having to duplicate it on every mount node.
  var __OWNIFY_DEFAULT_STYLE_NONCE = (typeof document !== 'undefined'
    && document.currentScript
    && document.currentScript.nonce) || null;

// ownify-chat-widget — programmatic API for build-system users.
//
// Two ways to use the widget:
//   1. Standalone <script src="https://ownify.ai/chat-widget.js"> on
//      any HTML page (zero build, src/standalone.js).
//   2. import { mountOwnifyChat } from 'ownify-chat-widget' inside
//      your React/Vue/Svelte/whatever app and call mountOwnifyChat
//      (rootEl, opts).
//
// The behaviour is identical: a small chat box that POSTs visitor
// messages to https://ownify.ai/api/chat/<slug> (or your own
// self-hosted endpoint). The receiver tenant signs the AAE envelope
// for its own public-chat traffic; visitors don't need accounts or DIDs.

const DEFAULT_BASE_URL = 'https://ownify.ai';
const DEFAULT_GREETING = 'Hi! Ask me anything.';
const DEFAULT_PLACEHOLDER = 'Type a message…';
const DEFAULT_FETCH_TIMEOUT_MS = 30_000;
const MIN_FETCH_TIMEOUT_MS = 1_000;
const MAX_FETCH_TIMEOUT_MS = 5 * 60_000;     // 5 min hard ceiling
const DEFAULT_SUBMIT_COOLDOWN_MS = 500;
const MAX_MESSAGE_LENGTH = 4096;
const MAX_REPLY_LENGTH = 10_000;             // truncate server replies past this
const VERSION = '0.1.3';

// Tightened from 0.1.1: method MUST start with a letter (W3C DID
// spec); identifier MUST start with an alphanumeric (forbidden
// `-foo` / `.foo` shapes some method specs reject anyway). Audit-only
// signal server-side; rejecting bad shapes here keeps spoofed values
// out of the receiver's audit log.
const DID_PATTERN = /^did:[a-z][a-z0-9]{0,31}:[A-Za-z0-9][A-Za-z0-9._-]{0,255}$/;

// Browser-side SSRF defence. If a malicious embedding page sets
// data-endpoint to a private/loopback host, the visitor's browser
// would emit the request — even if SOP/CORS blocks reading the
// response, the bare request is useful for service-fingerprinting
// on the visitor's machine. Block IPv4 + IPv6 literal forms,
// IPv4-mapped IPv6, IPv6 link-local + ULA, the most common DNS
// loopback names, and pure-numeric hostnames (decimal/hex IP
// notation). Trailing dots get stripped before matching.
const PRIVATE_HOST_PATTERN = new RegExp(
  '^(?:'
  + '127\\.'                                  // 127.0.0.0/8 IPv4 loopback
  + '|10\\.'                                  // 10.0.0.0/8 RFC1918
  + '|192\\.168\\.'                           // 192.168/16 RFC1918
  + '|169\\.254\\.'                           // 169.254/16 link-local + cloud metadata
  + '|0\\.0\\.0\\.0$'                         // unspecified
  + '|::$'                                    // IPv6 unspecified
  + '|::1$'                                   // IPv6 loopback (compressed)
  + '|0:0:0:0:0:0:0:0$'                       // IPv6 unspecified (expanded)
  + '|0:0:0:0:0:0:0:1$'                       // IPv6 loopback (expanded)
  + '|::ffff:127\\.'                          // IPv4-mapped IPv6 loopback
  + '|::ffff:10\\.'                           // IPv4-mapped IPv6 RFC1918
  + '|::ffff:192\\.168\\.'                    // IPv4-mapped IPv6 RFC1918
  + '|::ffff:169\\.254\\.'                    // IPv4-mapped IPv6 link-local
  + '|localhost$'                             // DNS loopback
  + '|localhost\\.localdomain$'               // DNS loopback (BSD/RHEL)
  + '|ip6-localhost$'                         // DNS loopback (IPv6)
  + '|ip6-loopback$'
  + ')',
  'i'
);
const PRIVATE_V4_172 = /^172\.(1[6-9]|2[0-9]|3[01])\./;
const PRIVATE_V6_FC00 = /^f[cd][0-9a-f]*:/i;          // fc00::/7 unique-local IPv6
const PRIVATE_V6_FE80 = /^fe[89ab][0-9a-f]*:/i;       // fe80::/10 link-local IPv6
const PRIVATE_V6_V4_MAPPED_172 = /^::ffff:172\.(1[6-9]|2[0-9]|3[01])\./;
// Pure-numeric / hex hostname → almost certainly a non-canonical IP
// encoding (decimal `2130706433` = 127.0.0.1, hex `0x7f000001` = same).
// Browsers resolve these to the underlying IP; reject as a class.
const NUMERIC_HOSTNAME = /^(?:\d+|0x[0-9a-f]+)$/i;

const STYLE_ID = 'ownify-chat-widget-styles';
const STYLES = ''
  + '.ow-chat{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;'
  + 'border:1px solid var(--ow-border,#2a2a2a);border-radius:12px;background:var(--ow-bg,#0a0a0a);'
  + 'color:var(--ow-fg,#e6e6e6);max-width:560px;display:flex;flex-direction:column;height:480px}'
  + '.ow-chat-log{flex:1;overflow-y:auto;padding:14px;display:flex;flex-direction:column;gap:10px}'
  + '.ow-chat-msg{max-width:85%;padding:8px 12px;border-radius:10px;line-height:1.5;font-size:14px;white-space:pre-wrap;word-wrap:break-word}'
  + '.ow-chat-msg.user{align-self:flex-end;background:var(--ow-accent,#3b82f6);color:#fff}'
  + '.ow-chat-msg.agent{align-self:flex-start;background:var(--ow-msg-bg,#1a1a1a)}'
  + '.ow-chat-msg.error{align-self:flex-start;background:#3a1a1a;color:#ff8a8a;font-size:13px}'
  + '.ow-chat-form{display:flex;gap:8px;padding:12px;border-top:1px solid var(--ow-border,#2a2a2a)}'
  + '.ow-chat-input{flex:1;background:var(--ow-input-bg,#1a1a1a);color:inherit;border:1px solid var(--ow-border,#2a2a2a);'
  + 'border-radius:8px;padding:8px 12px;font-size:14px;font-family:inherit;outline:none}'
  + '.ow-chat-input:focus{border-color:var(--ow-accent,#3b82f6)}'
  + '.ow-chat-send{background:var(--ow-accent,#3b82f6);color:#fff;border:none;border-radius:8px;'
  + 'padding:8px 16px;font-size:14px;font-weight:500;cursor:pointer}'
  + '.ow-chat-send:disabled{opacity:0.5;cursor:wait}'
  + '.ow-chat-meta{font-size:11px;color:var(--ow-meta,#888);text-align:center;padding:8px;border-top:1px solid var(--ow-border,#2a2a2a)}'
  + '.ow-chat-meta a{color:inherit}'
  // Markdown rendering inside agent bubbles. white-space:pre-wrap on
  // .ow-chat-msg means literal newlines get rendered as breaks already;
  // these rules give the parsed markdown elements sensible spacing
  // without pulling in a stylesheet's worth of opinions.
  + '.ow-chat-msg p{margin:0 0 0.5em 0}'
  + '.ow-chat-msg p:last-child{margin-bottom:0}'
  + '.ow-chat-msg h1,.ow-chat-msg h2,.ow-chat-msg h3,.ow-chat-msg h4,.ow-chat-msg h5,.ow-chat-msg h6{margin:0.6em 0 0.3em 0;font-size:1.05em;font-weight:600}'
  + '.ow-chat-msg h1:first-child,.ow-chat-msg h2:first-child,.ow-chat-msg h3:first-child{margin-top:0}'
  + '.ow-chat-msg ul,.ow-chat-msg ol{margin:0.3em 0 0.5em 0;padding-left:1.4em}'
  + '.ow-chat-msg li{margin:0.15em 0}'
  + '.ow-chat-msg blockquote{margin:0.3em 0;padding:0 0 0 0.8em;border-left:3px solid var(--ow-border,#2a2a2a);color:var(--ow-meta,#888)}'
  + '.ow-chat-msg code{background:rgba(127,127,127,0.18);padding:1px 5px;border-radius:4px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:0.92em}'
  + '.ow-chat-msg pre{background:rgba(127,127,127,0.12);padding:8px 10px;border-radius:6px;overflow-x:auto;margin:0.4em 0;white-space:pre}'
  + '.ow-chat-msg pre code{background:transparent;padding:0;font-size:0.85em}'
  + '.ow-chat-msg a{color:var(--ow-link,#5da7ff);text-decoration:underline}'
  + '.ow-chat-msg strong{font-weight:600}'
  + '.ow-chat-msg em{font-style:italic}'
  + '.ow-chat-msg table{border-collapse:collapse;margin:0.4em 0;font-size:0.92em;display:block;max-width:100%;overflow-x:auto}'
  + '.ow-chat-msg th,.ow-chat-msg td{border:1px solid var(--ow-border,#2a2a2a);padding:4px 9px;text-align:left;vertical-align:top}'
  + '.ow-chat-msg th{background:rgba(127,127,127,0.12);font-weight:600}'
  + '.ow-chat-msg tbody tr:nth-child(even) td{background:rgba(127,127,127,0.04)}'
  // Typing indicator: three bouncing dots while a reply is in flight.
  // Animation is opacity-only on a fixed transform so layout doesn\'t
  // shift, and uses prefers-reduced-motion friendly behaviour by
  // staying within the bubble\'s natural height.
  + '.ow-chat-msg.ow-chat-typing{padding:10px 14px;display:inline-flex;align-items:center;gap:4px}'
  + '.ow-chat-typing-dot{display:inline-block;width:6px;height:6px;background:var(--ow-fg,#bbb);border-radius:50%;opacity:0.35;animation:ow-chat-typing-anim 1.2s ease-in-out infinite}'
  + '.ow-chat-typing-dot:nth-child(2){animation-delay:0.18s}'
  + '.ow-chat-typing-dot:nth-child(3){animation-delay:0.36s}'
  + '@keyframes ow-chat-typing-anim{0%,80%,100%{opacity:0.25}40%{opacity:1}}';

function ensureStyles(doc, nonce) {
  if (doc.getElementById(STYLE_ID)) return;
  const style = doc.createElement('style');
  style.id = STYLE_ID;
  style.textContent = STYLES;
  // CSP-strict pages can pass `styleNonce` so the inline <style> is
  // allowed under a nonce-based style-src directive.
  if (nonce) style.nonce = String(nonce);
  doc.head.appendChild(style);
}

// Validate an endpoint URL. Rejects non-http(s), embedded credentials,
// private/loopback IP literals, and any URL that fails to parse.
// Defends against an attacker who can clobber data-endpoint on the
// mount node — either redirecting messages to a phishing endpoint
// or pointing at the visitor's local services for fingerprinting.
function validateEndpoint(urlStr) {
  let u;
  try { u = new URL(urlStr); } catch { return false; }
  if (u.protocol !== 'http:' && u.protocol !== 'https:') return false;
  if (u.username || u.password) return false;
  // Strip trailing dot (e.g. `localhost.` resolves identically to
  // `localhost` in browsers) before matching.
  const host = u.hostname.toLowerCase().replace(/\.$/, '');
  if (NUMERIC_HOSTNAME.test(host)) return false;
  if (PRIVATE_HOST_PATTERN.test(host)) return false;
  if (PRIVATE_V4_172.test(host)) return false;
  if (PRIVATE_V6_FC00.test(host)) return false;
  if (PRIVATE_V6_FE80.test(host)) return false;
  if (PRIVATE_V6_V4_MAPPED_172.test(host)) return false;
  return true;
}

/**
 * Mount the chat widget onto a DOM element.
 *
 * @param {HTMLElement} root
 * @param {object} opts
 *   @param {string} opts.slug                — REQUIRED. Receiver tenant slug.
 *   @param {string} [opts.baseUrl]           — default 'https://ownify.ai'
 *   @param {string} [opts.endpoint]          — overrides baseUrl entirely
 *   @param {string} [opts.greeting]
 *   @param {string} [opts.placeholder]
 *   @param {string} [opts.callerDid]         — optional X-Caller-DID (audit-only)
 *   @param {string} [opts.client]            — X-Ownify-Client header value
 *   @param {string} [opts.styleNonce]        — CSP nonce for the injected <style>
 *   @param {number} [opts.fetchTimeoutMs=30000]
 *   @param {number} [opts.submitCooldownMs=500] — debounce between user submits
 *   @param {number} [opts.maxMessageLength=4096]
 *
 * @returns {{ destroy: () => void }}
 */
// ── Safe-by-construction markdown renderer ────────────────────────────────
// Subset supported: paragraphs, line breaks, **bold**, *italic*, `code`,
// fenced ```code blocks```, # ## ### headings, - bullet lists, 1. ordered
// lists, > blockquotes, [text](url). Output uses createElement +
// textContent only — never innerHTML, no eval, no DOM-from-string. URLs
// in links are restricted to http(s) + relative; anything else degrades
// to plain text. Safe to feed adversarial agent output.
const MD_INLINE_SPECIALS = '`*_[';
function renderMarkdownSafe(src, container) {
  while (container.firstChild) container.removeChild(container.firstChild);
  if (typeof src !== 'string' || src.length === 0) return;
  const lines = src.split('\n');
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    // Fenced code block
    if (/^\s*```/.test(line)) {
      const lang = line.replace(/^\s*```/, '').trim();
      i++;
      const buf = [];
      while (i < lines.length && !/^\s*```/.test(lines[i])) { buf.push(lines[i]); i++; }
      if (i < lines.length) i++;
      const pre = document.createElement('pre');
      const code = document.createElement('code');
      if (lang && /^[a-zA-Z0-9_-]{1,32}$/.test(lang)) code.dataset.lang = lang;
      code.textContent = buf.join('\n');
      pre.appendChild(code);
      container.appendChild(pre);
      continue;
    }
    // Table: detect a `|`-leading row whose successor is a separator
    // line (`|---|---|` or `| --- | :--: |` etc). Without this, a
    // multi-line markdown table gets collapsed into a single paragraph
    // because each `| ... |` line wasn\'t recognised as a block-break.
    if (/^\s*\|/.test(line) && i + 1 < lines.length
        && /^\s*\|?\s*:?-{1,}:?\s*(\|\s*:?-{1,}:?\s*)+\|?\s*$/.test(lines[i + 1])) {
      const splitRow = (raw) => {
        const trimmed = raw.replace(/^\s*\|/, '').replace(/\|\s*$/, '');
        return trimmed.split('|').map((c) => c.trim());
      };
      const headerCells = splitRow(line);
      i += 2; // header + separator
      const dataRows = [];
      while (i < lines.length && /^\s*\|/.test(lines[i])) {
        dataRows.push(splitRow(lines[i]));
        i++;
      }
      const tbl = document.createElement('table');
      const thead = document.createElement('thead');
      const trH = document.createElement('tr');
      for (const cell of headerCells) {
        const th = document.createElement('th');
        _renderInlineMd(cell, th);
        trH.appendChild(th);
      }
      thead.appendChild(trH);
      tbl.appendChild(thead);
      const tbody = document.createElement('tbody');
      for (const row of dataRows) {
        const tr = document.createElement('tr');
        // pad / truncate to header width so a malformed row doesn\'t
        // produce an uneven table
        const cols = row.length === headerCells.length
          ? row
          : row.slice(0, headerCells.length).concat(
              new Array(Math.max(0, headerCells.length - row.length)).fill(''));
        for (const cell of cols) {
          const td = document.createElement('td');
          _renderInlineMd(cell, td);
          tr.appendChild(td);
        }
        tbody.appendChild(tr);
      }
      tbl.appendChild(tbody);
      container.appendChild(tbl);
      continue;
    }
    // Heading
    const h = /^(#{1,6})\s+(.+)$/.exec(line);
    if (h) {
      const node = document.createElement('h' + h[1].length);
      _renderInlineMd(h[2], node);
      container.appendChild(node);
      i++;
      continue;
    }
    // Blockquote (collapses adjacent > lines into one block)
    if (/^>\s?/.test(line)) {
      const buf = [];
      while (i < lines.length && /^>\s?/.test(lines[i])) {
        buf.push(lines[i].replace(/^>\s?/, ''));
        i++;
      }
      const bq = document.createElement('blockquote');
      _renderInlineMd(buf.join(' '), bq);
      container.appendChild(bq);
      continue;
    }
    // Unordered list
    if (/^\s*[-*]\s+/.test(line)) {
      const ul = document.createElement('ul');
      while (i < lines.length && /^\s*[-*]\s+/.test(lines[i])) {
        const li = document.createElement('li');
        _renderInlineMd(lines[i].replace(/^\s*[-*]\s+/, ''), li);
        ul.appendChild(li);
        i++;
      }
      container.appendChild(ul);
      continue;
    }
    // Ordered list
    if (/^\s*\d+\.\s+/.test(line)) {
      const ol = document.createElement('ol');
      while (i < lines.length && /^\s*\d+\.\s+/.test(lines[i])) {
        const li = document.createElement('li');
        _renderInlineMd(lines[i].replace(/^\s*\d+\.\s+/, ''), li);
        ol.appendChild(li);
        i++;
      }
      container.appendChild(ol);
      continue;
    }
    // Blank line — paragraph separator
    if (line.trim() === '') { i++; continue; }
    // Paragraph: collect consecutive non-block lines
    const buf = [];
    while (i < lines.length) {
      const l = lines[i];
      if (l.trim() === '') break;
      if (/^\s*(```|#{1,6}\s|>\s?|[-*]\s|\d+\.\s)/.test(l)) break;
      buf.push(l);
      i++;
    }
    const p = document.createElement('p');
    _renderInlineMd(buf.join(' '), p);
    container.appendChild(p);
  }
}

// Inline tokenizer: greedy match on `code`, **bold**, *italic*, [text](url).
// Recursion depth bounded by maxDepth so adversarial nested input can't blow
// the stack.
function _renderInlineMd(text, parent, depth) {
  const d = depth || 0;
  if (d > 6) { parent.appendChild(document.createTextNode(text)); return; }
  let pos = 0;
  while (pos < text.length) {
    const remain = text.slice(pos);
    let m;
    // Code span
    if ((m = /^`([^`\n]+)`/.exec(remain))) {
      const node = document.createElement('code');
      node.textContent = m[1];
      parent.appendChild(node);
      pos += m[0].length;
      continue;
    }
    // Bold (** or __)
    if ((m = /^(\*\*|__)([\s\S]+?)\1/.exec(remain))) {
      const node = document.createElement('strong');
      _renderInlineMd(m[2], node, d + 1);
      parent.appendChild(node);
      pos += m[0].length;
      continue;
    }
    // Italic (single * or _)
    if ((m = /^(\*|_)([^*_\n]+?)\1/.exec(remain))) {
      const node = document.createElement('em');
      _renderInlineMd(m[2], node, d + 1);
      parent.appendChild(node);
      pos += m[0].length;
      continue;
    }
    // Link [text](url)
    if ((m = /^\[([^\]\n]+)\]\(([^)\s]+)\)/.exec(remain))) {
      const url = m[2];
      // Strict URL safety: http(s)://… or relative path. Reject
      // javascript:, data:, vbscript:, and bare schemes by anchor.
      const safe = /^https?:\/\//i.test(url) || /^\//.test(url);
      const dangerous = /^(javascript|data|vbscript|file):/i.test(url);
      if (safe && !dangerous) {
        const a = document.createElement('a');
        a.href = url;
        a.textContent = m[1];
        a.rel = 'noopener noreferrer nofollow';
        a.target = '_blank';
        parent.appendChild(a);
      } else {
        parent.appendChild(document.createTextNode(m[0]));
      }
      pos += m[0].length;
      continue;
    }
    // Bare URL autolink. Some LLMs emit URLs without [text](url)
    // syntax (e.g. CJK-bracketed 【https://...】 or inline plain
    // links). Recognise http(s)://… up to whitespace or a closing
    // bracket-class char, then strip trailing punctuation that\'s
    // almost always sentence punctuation rather than part of the URL.
    if ((m = /^(https?:\/\/[^\s<>"【】\[\]]+)/i.exec(remain))) {
      let url = m[1];
      // Drop common trailing punctuation: . , ; : ! ? ) ] 】 >
      while (url.length > 8 && /[.,;:!?)\]】>]$/.test(url)) {
        url = url.slice(0, -1);
      }
      // Same safety check as the bracketed-link form. javascript:
      // / data: can\'t actually appear after http:// but the
      // dangerous-prefix test is cheap defence-in-depth.
      const safe = /^https?:\/\//i.test(url);
      const dangerous = /^(javascript|data|vbscript|file):/i.test(url);
      if (safe && !dangerous) {
        const a = document.createElement('a');
        a.href = url;
        a.textContent = url;
        a.rel = 'noopener noreferrer nofollow';
        a.target = '_blank';
        parent.appendChild(a);
        pos += url.length;
        continue;
      }
    }
    // Plain text — chunk until next inline special OR a bare-URL
    // boundary (so the autolinker above can match on the next pass).
    let next = remain.length;
    for (let j = 1; j < remain.length; j++) {
      if (MD_INLINE_SPECIALS.indexOf(remain[j]) !== -1) { next = j; break; }
    }
    const httpIdx = remain.search(/https?:\/\//i);
    if (httpIdx > 0 && httpIdx < next) next = httpIdx;
    const end = next;
    parent.appendChild(document.createTextNode(remain.slice(0, end)));
    pos += end;
  }
}

function mountOwnifyChat(root, opts) {
  if (!root || typeof root !== 'object' || root.nodeType !== 1) {
    throw new Error('mountOwnifyChat: root must be an HTMLElement');
  }
  if (!opts || typeof opts.slug !== 'string' || opts.slug.trim().length === 0) {
    throw new Error('mountOwnifyChat: opts.slug is required (non-empty string)');
  }
  if (root.dataset && root.dataset.ownifyChatInit === '1') {
    throw new Error('mountOwnifyChat: this root is already mounted — call destroy() first');
  }

  const slug = opts.slug.trim();
  const baseUrl = String(opts.baseUrl || DEFAULT_BASE_URL).replace(/\/+$/, '');
  const endpoint = opts.endpoint != null
    ? String(opts.endpoint)
    : (baseUrl + '/api/chat/' + encodeURIComponent(slug));
  if (!validateEndpoint(endpoint)) {
    throw new Error('mountOwnifyChat: endpoint must be a valid http(s) URL without embedded credentials');
  }

  // Warn loudly when callers pass non-strings to user-visible
  // options — easier to catch a `{text: 'hi'}` typo than to debug
  // why "[object Object]" is rendered in the chat.
  for (const k of ['greeting', 'placeholder', 'client']) {
    if (opts[k] != null && typeof opts[k] !== 'string') {
      try { console.warn('ownify-chat: opts.' + k + ' should be a string, got ' + typeof opts[k]); } catch { /* ignore */ }
    }
  }
  const greeting = String(opts.greeting || DEFAULT_GREETING);
  const placeholder = String(opts.placeholder || DEFAULT_PLACEHOLDER);
  const client = String(opts.client || ('ownify-chat-widget@' + VERSION));
  // Bound fetchTimeoutMs to a sane window: a value like Number.MAX_VALUE
  // would silently clamp to setTimeout's ~24-day max and effectively
  // disable the timeout. 1s minimum (sub-1s is a clock-skew bug),
  // 5min ceiling (longer is almost never legitimate for chat).
  const fetchTimeoutMs = Number.isFinite(opts.fetchTimeoutMs)
    && opts.fetchTimeoutMs >= MIN_FETCH_TIMEOUT_MS
    && opts.fetchTimeoutMs <= MAX_FETCH_TIMEOUT_MS
    ? opts.fetchTimeoutMs : DEFAULT_FETCH_TIMEOUT_MS;
  const submitCooldownMs = Number.isFinite(opts.submitCooldownMs) && opts.submitCooldownMs >= 0
    ? opts.submitCooldownMs : DEFAULT_SUBMIT_COOLDOWN_MS;
  const maxMessageLength = Number.isInteger(opts.maxMessageLength) && opts.maxMessageLength > 0
    ? opts.maxMessageLength : MAX_MESSAGE_LENGTH;
  // credentials: opt-in, default 'omit'. Public chat is unauth-by-design,
  // so cookies don't travel to the chat endpoint. Operators with a
  // same-origin / authenticated chat backend can pass 'same-origin'
  // or 'include' explicitly.
  const credentials = ['omit', 'same-origin', 'include'].includes(opts.credentials)
    ? opts.credentials : 'omit';

  // Validate caller DID shape before forwarding. Audit-only signal
  // server-side; rejecting bad shapes here keeps spoofed values out
  // of the receiver's audit log.
  let callerDid = null;
  if (opts.callerDid != null) {
    const candidate = String(opts.callerDid);
    if (DID_PATTERN.test(candidate)) callerDid = candidate;
  }

  ensureStyles(root.ownerDocument || document, opts.styleNonce);

  // Build DOM via createElement — never via innerHTML. Eliminates the
  // entire XSS class (no future edit can accidentally interpolate
  // attacker-controlled HTML) and makes destroy() cleaner.
  const doc = root.ownerDocument || document;
  const container = doc.createElement('div');
  container.className = 'ow-chat';

  const log = doc.createElement('div');
  log.className = 'ow-chat-log';
  log.setAttribute('role', 'log');
  log.setAttribute('aria-live', 'polite');
  container.appendChild(log);

  const form = doc.createElement('form');
  form.className = 'ow-chat-form';
  const input = doc.createElement('input');
  input.className = 'ow-chat-input';
  input.type = 'text';
  input.autocomplete = 'off';
  input.maxLength = maxMessageLength;
  input.placeholder = placeholder;
  const send = doc.createElement('button');
  send.className = 'ow-chat-send';
  send.type = 'submit';
  send.textContent = 'Send';
  form.appendChild(input);
  form.appendChild(send);
  container.appendChild(form);

  const meta = doc.createElement('div');
  meta.className = 'ow-chat-meta';
  meta.appendChild(doc.createTextNode('Powered by '));
  const metaLink = doc.createElement('a');
  metaLink.href = 'https://ownify.ai';
  metaLink.target = '_blank';
  metaLink.rel = 'noopener noreferrer';
  metaLink.textContent = 'ownify';
  meta.appendChild(metaLink);
  meta.appendChild(doc.createTextNode(' · agent-to-agent'));
  container.appendChild(meta);

  // Replace any existing children of root with our container.
  while (root.firstChild) root.removeChild(root.firstChild);
  root.appendChild(container);
  if (root.dataset) root.dataset.ownifyChatInit = '1';

  addMsg('agent', greeting);

  function addMsg(role, text) {
    const div = doc.createElement('div');
    div.className = 'ow-chat-msg ' + role;
    div.textContent = text;
    log.appendChild(div);
    log.scrollTop = log.scrollHeight;
    return div;
  }

  function setBusy(busy) {
    send.disabled = busy;
    input.disabled = busy;
  }

  // Track in-flight requests so destroy() can abort them and so
  // closures don't try to mutate detached DOM after teardown.
  let inflightController = null;
  let lastSubmitAt = 0;
  let destroyed = false;

  async function onSubmit(e) {
    e.preventDefault();
    if (destroyed) return;
    const now = Date.now();
    if (now - lastSubmitAt < submitCooldownMs) return;
    lastSubmitAt = now;

    let msg = input.value.trim();
    if (!msg) return;
    if (msg.length > maxMessageLength) msg = msg.slice(0, maxMessageLength);
    input.value = '';
    addMsg('user', msg);
    setBusy(true);
    // Pending bubble with an animated typing indicator (3 bouncing
    // dots) so the visitor sees the agent is working, not stuck.
    // True token streaming would need an SSE-aware A2A protocol on
    // the receiver — out of scope here; this is the cheap UX win.
    const pending = addMsg('agent', '');
    pending.classList.add('ow-chat-typing');
    for (let __i = 0; __i < 3; __i++) {
      const __dot = doc.createElement('span');
      __dot.className = 'ow-chat-typing-dot';
      pending.appendChild(__dot);
    }

    const ac = new AbortController();
    inflightController = ac;
    const timer = setTimeout(() => {
      try { ac.abort(); } catch { /* ignore */ }
    }, fetchTimeoutMs);

    try {
      const headers = {
        'content-type': 'application/json',
        accept: 'application/json',
        'x-ownify-client': client,
      };
      if (callerDid) headers['x-caller-did'] = callerDid;
      const r = await fetch(endpoint, {
        method: 'POST',
        headers,
        body: JSON.stringify({ message: msg }),
        credentials,
        signal: ac.signal,
        redirect: 'error',
        // Don't leak the embedding page's URL/path/query to the chat
        // endpoint via Referer. Operators who need referrer for
        // analytics can reverse-proxy and add their own.
        referrerPolicy: 'no-referrer',
      });
      if (destroyed) return;
      // Reply / error is about to land — drop the typing indicator so
      // the bubble can render its real content.
      pending.classList.remove('ow-chat-typing');
      // Check status BEFORE parsing the body. A malicious / compromised
      // backend returning HTTP 500 with a multi-MB JSON payload would
      // freeze the visitor's tab if we await r.json() unconditionally.
      // Cancel the body stream on error so we never read it into memory.
      if (!r.ok) {
        try { if (r.body && r.body.cancel) r.body.cancel(); } catch { /* ignore */ }
        try { console.error('ownify-chat request failed: HTTP ' + r.status); } catch { /* ignore */ }
        pending.classList.remove('agent');
        pending.classList.add('error');
        pending.textContent = 'Something went wrong. Please try again.';
        return;
      }
      const ct = (r.headers.get('content-type') || '').toLowerCase();
      const body = ct.includes('application/json') ? await r.json() : await r.text();
      if (destroyed) return;
      // Pull the agent's reply out of the response. Reject arrays
      // (response is a single message, not a sequence) and null.
      const reply = (body && typeof body === 'object' && !Array.isArray(body)
        && (body.message || body.reply || body.content || body.text))
        || (typeof body === 'string' ? body : null);
      if (typeof reply === 'string' && reply.length > 0) {
        // Cap rendered reply size — defends the visitor's browser
        // against a malicious / compromised backend streaming a
        // huge reply that would freeze the tab.
        const capped = reply.length > MAX_REPLY_LENGTH
          ? reply.slice(0, MAX_REPLY_LENGTH) + '…'
          : reply;
        // Render markdown safely (createElement + textContent only;
        // no innerHTML; URL allowlist on links).
        renderMarkdownSafe(capped, pending);
      } else {
        try { console.warn('ownify-chat: unexpected response shape (logged length only):', typeof body, (body && body.length) || 0); } catch { /* ignore */ }
        pending.textContent = 'Received an unexpected response.';
      }
    } catch (err) {
      if (destroyed) return;
      pending.classList.remove('ow-chat-typing');
      const aborted = err && (err.name === 'AbortError' || err.message === 'aborted');
      // Log only err.name (consistent with the HTTP-error path that
      // logs only the status). Avoids handing the full error object —
      // including its stack trace — to a console-overriding script
      // on the embedding page.
      try { console.error('ownify-chat:', aborted ? 'request timed out' : 'network error: ' + (err && err.name)); } catch { /* ignore */ }
      pending.classList.remove('agent');
      pending.classList.add('error');
      pending.textContent = aborted ? 'Request timed out.' : 'Network error. Please try again.';
    } finally {
      clearTimeout(timer);
      if (inflightController === ac) inflightController = null;
      if (!destroyed) {
        setBusy(false);
        try { input.focus(); } catch { /* ignore */ }
      }
    }
  }

  form.addEventListener('submit', onSubmit);

  function destroy() {
    if (destroyed) return;
    destroyed = true;
    form.removeEventListener('submit', onSubmit);
    if (inflightController) {
      try { inflightController.abort(); } catch { /* ignore */ }
      inflightController = null;
    }
    while (root.firstChild) root.removeChild(root.firstChild);
    if (root.dataset) delete root.dataset.ownifyChatInit;
    // Remove the cleanup hook we attached for SPA hosts.
    try { if (root._ownifyDestroy === destroy) delete root._ownifyDestroy; } catch { /* ignore */ }
  }

  // SPA-host cleanup hook. Standalone-IIFE consumers (script-tag
  // embeds) don't get the return value, so attach the destroy handle
  // to the mount node where they can find it. Documented in README.
  try { root._ownifyDestroy = destroy; } catch { /* ignore */ }

  return { destroy };
}

/**
 * Auto-bootstrap any element on the page with [data-ownify-chat] or
 * id="ownify-chat". Useful for non-build pages — but most of those
 * use the standalone <script> tag instead, which calls this on load.
 *
 * @param {object} [defaults]
 *   @param {string} [defaults.styleNonce] — used when the node
 *     itself doesn't carry data-style-nonce. Standalone bootstrap
 *     auto-fills this with document.currentScript.nonce so a CSP
 *     nonce on the <script> tag transparently propagates to the
 *     widget's inline <style> without the embedder having to
 *     duplicate the nonce on every mount node.
 */
function bootstrapOwnifyChat(defaults) {
  const opts = defaults && typeof defaults === 'object' ? defaults : {};
  const nodes = document.querySelectorAll('[data-ownify-chat], #ownify-chat');
  for (const node of nodes) {
    if (node.dataset.ownifyChatInit === '1') continue;
    try {
      // numeric data-* attrs come through as strings — coerce + drop
      // values that aren't finite (lets mountOwnifyChat fall back to
      // its own defaults rather than failing the bound check).
      const numAttr = (raw) => {
        const n = Number(raw);
        return Number.isFinite(n) ? n : undefined;
      };
      mountOwnifyChat(node, {
        slug: node.dataset.slug,
        baseUrl: node.dataset.baseUrl,
        endpoint: node.dataset.endpoint,
        greeting: node.dataset.greeting,
        placeholder: node.dataset.placeholder,
        callerDid: node.dataset.callerDid,
        // Per-node attribute wins; fall back to the default the
        // standalone bootstrap captured from <script nonce="...">
        styleNonce: node.dataset.styleNonce || opts.styleNonce,
        // data-credentials wasn't wired in 0.1.2 — fixed.
        credentials: node.dataset.credentials,
        // 0.1.4: numeric overrides exposed via data-* attrs so
        // operators on slow upstreams (e.g. self-hosted LLMs that
        // can take 30-120s per turn) can lift the timeout without
        // dropping into the JS API.
        fetchTimeoutMs: numAttr(node.dataset.fetchTimeoutMs),
        submitCooldownMs: numAttr(node.dataset.submitCooldownMs),
      });
    } catch (err) {
      try { console.warn('ownify-chat: failed to bootstrap node:', err && err.message); } catch { /* ignore */ }
    }
  }
}

  // Auto-bootstrap on DOMContentLoaded so a plain <script> tag works
  // without any inline call-out from the embedding page.
  function __ownifyBootstrap() {
    bootstrapOwnifyChat({ styleNonce: __OWNIFY_DEFAULT_STYLE_NONCE });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', __ownifyBootstrap);
  } else {
    __ownifyBootstrap();
  }
})();
